### ISSUE TITLE
Camera not responding in Home App

### ISSUE THREAD

**Issue by GoTeslaGo** [birkir/homebridge-plugin-eufy-security#1]
**Describe The Bug:**
Home app won't stream doorbell camera and just shows the camera is not responding. The logs in Homebridge show:

[12/1/2020, 12:38:01 PM] [eufy] Restoring existing accessory from cache: Doorbell
[12/1/2020, 12:41:48 PM] [eufy] Starting video stream: 1280 x 720, 30 fps, 299 kbps
[12/1/2020, 12:41:48 PM] [eufy] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/1/2020, 12:41:48 PM] [eufy] Stopped video stream.

When i click on the settings button of the camera within the Home app, it throws the following error and causes Homebridge to restart:

[12/1/2020, 12:42:13 PM] TypeError: callback is not a function
    at DoorbellPlatformAccessory.handleMuteGet (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/src/doorbell-platform-accessory.ts:183:5)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[12/1/2020, 12:42:13 PM] Got SIGTERM, shutting down Homebridge...

**Plugin Config:**

 {
            "name": "eufy",
            "username": "***@***.com",
            "password": "****",
            "platform": "EufySecurityHomebridgePlugin"
        }
```
**Environment:**

* **Plugin Version**:
* **Homebridge Version**: v1.1.6
* **Node.js Version**: 13.11.0
* **NPM Version**: 6.14.9
* **Operating System**: mac OS

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by birkir** [comment]
Try the 0.1.1 version now

**Comment by GoTeslaGo** [comment]
Updated to 0.1.1 but still not working:

[12/2/2020, 11:14:29 AM] [eufy] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Test
[12/2/2020, 11:14:31 AM] [eufy] Starting video stream: 1280 x 720, 30 fps, 299 kbps Test
[12/2/2020, 11:14:31 AM] [eufy] Failed to start stream: spawn ffmpeg ENOENT Test
[12/2/2020, 11:14:31 AM] [eufy] Stopped video stream. Test

**Comment by adekka** [comment]
just checking: do you have a battery doorbell?

The battery doorbell doesn't stream continiously. It need the doorbell being triggered in order to start the stream. Perhaps someting to mention in the readme.

**Comment by GoTeslaGo** [comment]
ah ok that makes sense then! Yes I have the battery doorbell but hardwired.

Would you be able to just expose the motion sensor of the doorbell? What I would like is when it detects motion, the porch light should turn on

**Comment by birkir** [comment]
It works with the Battery doorbell. You will get a white Eufy splash screen for a brief moment before the camera starts.

**Comment by GoTeslaGo** [comment]
ok so if someone presses the battery doorbell button, that's when I should see the video? sounds like I cannot continuously stream unless someone 'activates' the doorbell...do I have that right?

Also could you possibly expose just the motion sensor as Eufy has been able to do with their cameras? I have my Eufycams on HomeKit but only use them to detect activity and let the Eufy app handle all video so that enhancement for the doorbell would be great

**Comment by birkir** [comment]
Nope you can stream anytime

https://streamable.com/1uv1at

I don't have time these days, but I am happy to accept pull requests for those kind of features

**Comment by karesake** [comment]
Got this Error since the latest 0.1.3 @birkir

**Comment by blindbatts** [comment]
FWIW: Installing ffmpeg onto the VM hosting homebridge fixed this for me - would be useful to add to the install guide that it's required.

DietPi vm for me - apt-get install ffmpeg
