### ISSUE TITLE
registering a push token timed out

### ISSUE THREAD

**Issue by djrams10** [birkir/homebridge-plugin-eufy-security#10]
**Describe The Bug:**

-hello, sorry for my english i'm french. After having successfully displayed the video stream of the doorbell in homekit, after a few tries (3 tries), the stream no longer wanted to be displayed, but it is impossible to register with my login and password. homebridge displays that the token is time out, and on the Eufy application I no longer connect with my username and password, it indicates that the request has failed. I am completely stuck. I tried with my wife's guest account and it did exactly the same, all went well at the start and after 3 tries, reading the video stream, the token was time out in homebridge. So I am not disconnecting from my wife's ios application otherwise I think that when I should log in he will tell me the request has failed. Could you help me out, because now I'm even stuck with the EUFY ios app. Thank you in advance for your plugin that I have been waiting for a while.

**Logs:**

```
[12/12/2020, 7:24:44 AM] Loaded plugin: homebridge-plugin-eufy-security@0.1.4
[12/12/2020, 7:24:44 AM] Registering platform 'homebridge-plugin-eufy-security.EufySecurityHomebridgePlugin'
[12/12/2020, 7:24:44 AM] ---
[12/12/2020, 7:24:44 AM] Loaded plugin: homebridge-config-ui-x@4.36.0
[12/12/2020, 7:24:44 AM] Registering platform 'homebridge-config-ui-x.config'
[12/12/2020, 7:24:44 AM] ---
[12/12/2020, 7:24:44 AM] Loading 2 platforms...
[12/12/2020, 7:24:44 AM] [Config] Initializing config platform...
[12/12/2020, 7:24:44 AM] [Config] Running in Service Mode
[12/12/2020, 7:24:44 AM] [EufySecurityHomebridgePlugin] Initializing EufySecurityHomebridgePlugin platform...
[12/12/2020, 7:24:44 AM] [EufySecurityHomebridgePlugin] Finished initializing platform: undefined
[12/12/2020, 7:24:44 AM] [EufySecurityHomebridgePlugin] push client enabled
[12/12/2020, 7:24:44 AM] [EufySecurityHomebridgePlugin] credentials found. reusing them...
Setup Payload:
X-HM://0023ISYWYKJPP
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/12/2020, 7:24:44 AM] Homebridge is running on port 51716.
[12/12/2020, 7:24:45 AM] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100023 - Password entered wrong many times, please try again tomorrow
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[12/12/2020, 7:24:45 AM] [EufySecurityHomebridgePlugin] registered at eufy with: cXgFxOTETcsJ1g5oep2pYe:APA91bGWecRvtgNRI_mzX51ohbyf0txo5fTu4uZ5gFBoW9s2r43F5VvH38r9xgOBhcQPqC9ZbdunsoByTxbUWmTjCRgtwXljFZSCZvZ99mJ_RtgFmCYVhwhRMiNhV_Lnkh4pnM-uf6V8
[12/12/2020, 7:24:45 AM] [EufySecurityHomebridgePlugin] Executed didFinishLaunching callback
(node:816) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100023 - Password entered wrong many times, please try again tomorrow
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/12/2020, 7:25:04 AM] [EufySecurityHomebridgePlugin] registering a push token timed out
[12/12/2020, 7:25:16 AM] [EufySecurityHomebridgePlugin] failed to confirm push token
[12/12/2020, 7:25:46 AM] [EufySecurityHomebridgePlugin] failed to confirm push token
[12/12/2020, 7:26:16 AM] [EufySecurityHomebridgePlugin] failed to confirm push token
[12/12/2020, 7:26:46 AM] [EufySecurityHomebridgePlugin] failed to confirm push token
```

**Plugin Config:**

       "enablePush": true,
            "platform": "EufySecurityHomebridgePlugin",
            "password": "my password",
            "username": "my login"

**Screenshots:**

    
<img width="1268" alt="Capture d’écran 2020-12-12 à 07 47 55" src="https://user-images.githubusercontent.com/28505910/101977552-67b59080-3c4e-11eb-9cd8-7eb6bb74b685.png">

![IMG_213D1B018C06-1 3](https://user-images.githubusercontent.com/28505910/101977661-57ea7c00-3c4f-11eb-8b6d-b62ec5d98860.jpeg)

**Environment:**

* **Plugin Version**: v0.1.4
* **Homebridge Version**: v1.1.6
* **Node.js Version**: v14.15.0
* **NPM Version**: v6.14.9
* **Operating System**:  Docker Synology
* **Materiel**: Doorbell Eufy Battery

**Comment by KixAss** [comment]
Same problem here. URL https://security-app-eu.eufylife.com/v1/passport/login gives a 404

**Comment by jmwarren85** [comment]
Same issue. My Eufy account has now been locked out and I can't get back in.

**Comment by djrams10** [comment]
> Same issue. My Eufy account has now been locked out and I can't get back in.

My account came back active 48 hours later.

**Comment by Sheldor81** [comment]
I have the same problem with the wired bell.

**Comment by djrams10** [comment]
I stopped using the plugin until the problem is solved

**Comment by neumanns** [comment]
after 48 hours my account is back

**Comment by djrams10** [comment]
> after 48 hours my account is back

in my opinion the problem will come back if we use it.  anyone have a try?

**Comment by skazzyskills** [comment]
Same issue with me. Token error.

**Comment by paul-minssieux** [comment]
HI, I have the same issue. I see that our beloved developer is working on it as it's coming from the library that he is using to communicate with Eufy : https://github.com/JanLoebel/eufy-node-client/issues/21 
Keep us posted,

Thanks

**Comment by gchattha** [comment]
Same problem here

**Comment by djrams10** [comment]
thanks for the fix.  It’s much better already. I don’t have a token problem anymore.  but with me it works randomly.  the small sticker which refreshes every 10 seconds works perfectly and every time.  however the video stream works from time to time, it doesn’t show up for sure, I put the logs.  and the doorbell notification shows up in the logs but doesn't show up on my iPhone or HomePod.  thanks again

`[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] Video stream requested: 1280 x 720, 30 fps, 299 kbps Sonnette  true
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Sonnette 
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] Stream command: /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/ffmpeg-for-homebridge/ffmpeg -i rtmp://p2p-vir-8.eufylife.com/hls/VDgwMTBQMjMyMDE3MUQxM18wXzJf?time=1608701857&token=b22434825b545cfa012efc977ecd4d13 -an -sn -dn -codec:v libx264 -pix_fmt yuv420p -color_range mpeg -f rawvideo -preset ultrafast -filter:v scale=1280:720,scale='trunc(iw/2)*2':'trunc(ih/2)*2' -b:v 299k -payload_type 99 -ssrc 9159109 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params 54njCSOnkjaQhEUft5exnYTflacGP1OdJfWEu7UT srtp://192.168.86.39:58658?rtcpport=58658&pkt_size=1316 -vn -sn -dn -ssrc 2532454 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params HOxdls3TyQWpcy8e3AEa/ujNpOePTu2H0KiZ54bt srtp://192.168.86.39:53915?rtcpport=53915&pkt_size=188 -loglevel level+verbose Sonnette  true
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   built with gcc 9.3.0 (Alpine 9.3.0)
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libavutil      56. 51.100 / 56. 51.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libavcodec     58. 91.100 / 58. 91.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libavformat    58. 45.100 / 58. 45.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libavdevice    58. 10.100 / 58. 10.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libavfilter     7. 85.100 /  7. 85.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libswscale      5.  7.100 /  5.  7.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libswresample   3.  7.100 /  3.  7.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [info]   libpostproc    55.  7.100 / 55.  7.100
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [tcp @ 0x7ff5125f6d40] [verbose] Starting connection attempt to 99.83.182.161 port 1935
[12/23/2020, 6:32:38 AM] [EufySecurityHomebridgePlugin] [tcp @ 0x7ff5125f6d40] [verbose] Successfully connected to 99.83.182.161 port 1935`

**Comment by skazzyskills** [comment]
Also stopped working for me. :-(

(node:27034) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> 20022 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[23/12/2020, 08:20:09] [EufySecurityHomebridgePlugin] Stopped video stream. Front doorbell


Shawn Skalinski
sskalinski@icloud.com

**Comment by avielc** [comment]
Any ideas what's causing it? password complexity?

**Comment by skazzyskills** [comment]
> Any ideas what's causing it? password complexity?

So seems to be working for me now, but it has killed my indoor cameras internet connection and they're 'no response' now. Strange as I set up the doorbell as a guest account.

**Comment by avielc** [comment]
Thanks for the reply @skazzyskills - What did you do to make it work? 
Odd thing that internet connection issue, if I'll reach that stage, i'll let you know if I figure it out :)

**Comment by skazzyskills** [comment]
First of all thank you for working on this! I will definitely donate to you once this is up and running, so make sure you have a 'donate' button on the homebridge plugin install! I just uninstalled the plugin and waited, then it came back online. At the moment, my indoor cameras are showing blue this morning, so they seem to be back online; however, showing no response in Homekit, so not sure if I have to wait that out or not. I also don't have 'push' enabled. Do you advise I enable?
Oh wait..the cameras just went back offline again. So something's up there. Let me know if and how I can provide you more info if you need it.

**Comment by skazzyskills** [comment]
@avielc 
Also getting these errors: 
(node:27288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:27288) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo EAI_AGAIN security-app.eufylife.com
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

**Comment by skazzyskills** [comment]
If I do enable push, it also says 'registering push token timed out'. FYI.

**Comment by avielc** [comment]
yea, I have the same issue with enabling the push. 
and just to make sure you know, i'm not the developer here, so feel free to contribute to him whenever you wish to. 
I also stopped using the plugin until it'll work again :-\ unfortunately I had to go back to ffmpeg plugin which isn't so stable and doesn't support 2 way audio on homekit....

**Comment by skazzyskills** [comment]
Ah ok. Ya there’s no two way audio yet with this either. 

Shawn Skalinski
sskalinski@icloud.com

**Comment by technikosoldat** [comment]
@djrams10 Salut, j’ai le même problème que toi. Le plugin ne marchait plus. Je l’ai donc désinstalle et réinstalle. Depuis ça ne s’affiche plus sur HomeKit et quand je vais sur l’appli Eufy, ça m’a déconnecté et je ne peux plus me connecter. Ils m’ont bloqué ?

**Comment by djrams10** [comment]
Oui ça va durer 24h

**Comment by jamestowers** [comment]
Was there any progress with this? I'm still getting the `failed to confirm push token` error with a new install.
