### ISSUE TITLE
Plugin is not loading due to a request failure

### ISSUE THREAD

**Issue by MBL77** [birkir/homebridge-plugin-eufy-security#13]
After configuring the plugin with my Eufy credentials and restarting Homebridge the plugin is not loading due to a request failure. It this an issue or am I doing something wrong.

Here's the specific error section from the Log

UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app-eu.eufylife.com/v1/passport/login -> 26052 - need validate code
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And I have configured the pluging like this:

{
       "name": "Eufy deurbel",
       "username": "my email address",
       "password": "my password",
       "platform": "EufySecurityHomebridgePlugin"
}

* **Plugin Version**: v0.1.4 
* **Homebridge Version**: v1.2.4
* **Node.js Version**: v14.15.1
* **NPM Version**: v6.14.8
* **Operating System**: Docker

**Comment by MBL77** [comment]
Ok, solved it! 2FA got in the way. After disabling it, it worked.
My apologies. Keep up the good work!
