### ISSUE TITLE
I just had to say a big THANK YOU to the developer for doing this plugin (though at the moment it's not working for me)

### ISSUE THREAD

**Issue by skazzyskills** [birkir/homebridge-plugin-eufy-security#15]
THANK YOU for having a go at this plugin! Hope I can get it working. :-)

**Describe Your Problem:**
Plugin installed fine, but getting error (see logs below).

**Logs:**
[15/12/2020, 09:03:42] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10304) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10304) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10304) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15/12/2020, 09:04:01] [EufySecurityHomebridgePlugin] registering a push token timed out
[15/12/2020, 09:04:12] [EufySecurityHomebridgePlugin] failed to confirm push token

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* Homebridge v1.2.4
* **Node.js Version**: 
* v14.15.1
* **NPM Version**: 
* v6.14.8
* **Operating System**: 
*Raspbian Pi

**Comment by gchattha** [comment]
I'm having the same problem unfortunately. This is also locking me out of mysecurity.eufylife.com although the account works fine on www.eufylife.com. If I disable the plugin overnight, my login at mysecurity works again but soon as I re-enable, it breaks. 

[12/16/2020, 8:36:22 AM] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1424) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/16/2020, 8:36:27 AM] [EufySecurityHomebridgePlugin] registering a push token timed out
[12/16/2020, 8:36:52 AM] [EufySecurityHomebridgePlugin] failed to confirm push token

**Comment by jabackes** [comment]
I too am having this problem on my system, I was never functional before, but after updating to HB 1.1.7 on a mac-mini - 
Mac OS Yosemite
Node.js Version | v14.14.0
NPM version v6.14.8
I get much the same errors as above. i am able to log into the app on my phone as well as the website using the credentials I've provided. i did remove and reinstall the plugin. is there a file or files I could go hunt for to do a completely clean install? could that help?

**Comment by adaofeliz** [comment]
+1 It seems that there is some sort of login rate limit from Eufy cloud locking the account, we should change the plugin to reduce the amount of login requests.

**Comment by melono6** [comment]
Same issue, do we know what the rate limit is, or how long you get locked out for?

**Comment by MaxWinterstein** [comment]
@melono6 are you unlocked? any news?

**Comment by skazzyskills** [comment]
Yes, I uninstall the plug-in and reinstalled it.

Shawn Skalinski
sskalinski@icloud.com

**Comment by sfguyfor20** [comment]
I'm getting this same error, I'm using the latest version of hoobs... 3.3.5, node version 12.16.3... I've uninstalled, I've reset hoobs and started fresh... each time I install this plugin, I get this error... Any help would be great.... thanks

**Comment by skazzyskills** [comment]
Stopped working for me too. Getting notifications but unresponsive. 

Shawn Skalinski
***@***.***

**Comment by cardejor000** [comment]
wtf

**Comment by cardejor000** [comment]
This plug-in shouldn't be this difficult. All of my config is correct but only receive this error. 

Plugin Eufy Security BridgeWARNINGunhandled rejection: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 10000 - Failed to request.
