### ISSUE TITLE
Unable to work

### ISSUE THREAD

**Issue by koen1971** [birkir/homebridge-plugin-eufy-security#19]
Been experimenting but can't get it to work. I see the Doorbell in Homekit but no video. When doorbell is used also no message. I've disabled 2FA in the app. Made a new user. I het the following message in the log;

[12/23/2020, 6:56:06 AM] [EufySecurityHomebridgePlugin] Restoring existing accessory from cache: Deurbel
[12/23/2020, 6:56:06 AM] [EufySecurityHomebridgePlugin] Restoring existing accessory from cache: Oprit
[12/23/2020, 6:56:30 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/23/2020, 6:56:30 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 6:56:30 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/23/2020, 6:57:19 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/23/2020, 6:57:19 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 6:57:19 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/23/2020, 10:58:55 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/23/2020, 10:58:55 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 10:58:55 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/23/2020, 10:58:58 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 10:58:59 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Oprit
[12/23/2020, 11:48:45 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 11:48:45 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Oprit
[12/23/2020, 11:48:48 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/23/2020, 11:48:48 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 11:48:48 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/23/2020, 11:49:47 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/23/2020, 11:49:47 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Deurbel
[12/23/2020, 11:49:47 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel

**Comment by skazzyskills** [comment]
Was working for me, now not working:

(node:27034) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> 20022 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[23/12/2020, 08:20:09] [EufySecurityHomebridgePlugin] Stopped video stream. Front doorbell

**Comment by koen1971** [comment]
I've created a new guest account. Get no errors now, but there is still no stream anon notification.

[12/24/2020, 11:25:21 AM] [EufySecurityHomebridgePlugin] Restoring existing accessory from cache: Deurbel
[12/24/2020, 11:26:31 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/24/2020, 11:27:01 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/24/2020, 11:27:26 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/24/2020, 11:27:56 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
[12/24/2020, 11:35:24 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/24/2020, 11:35:53 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel

**Comment by skazzyskills** [comment]
What do you mean you created a guest account? Do you mean you created another UV account and invited that account to your doorbell? That’s what I did too. But it doesn’t really make a difference. I think either way works fine but I’m doing it out of security issues. What do you mean no stream? anon?

Shawn Skalinski
sskalinski@icloud.com

**Comment by koen1971** [comment]
Yes guest account because I read that you can not use two accounts at the same time. 
with stream I mean I see no video. Also no notification when doorbell is pushed. 
I see ffmpeg error so I think there is some problem with resolution or camera look up
