### ISSUE TITLE
Stopped working, getting this error. Anyone else homebase getting solid red light?

### ISSUE THREAD

**Issue by skazzyskills** [birkir/homebridge-plugin-eufy-security#20]
**Describe The Bug:**
no response error all of a sudden. This is consistent.
(node:27034) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> 20022 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[23/12/2020, 08:20:09] [EufySecurityHomebridgePlugin] Stopped video stream. Front doorbell

**To Reproduce:**
Anytime you try to stream

**Expected behavior:**

**Logs:**
(node:27034) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> 20022 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:27034) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
[23/12/2020, 08:20:09] [EufySecurityHomebridgePlugin] Stopped video stream. Front doorbell
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by rdustinb** [comment]
Same. My HomeBridge is permanently boot looping now.

```[23/12/2020, 16:54:34] Homebridge is running on port 51140.
[23/12/2020, 16:54:34] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23/12/2020, 16:54:34] [EufySecurityHomebridgePlugin] failed to confirm push token
[23/12/2020, 16:54:34] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at PushClient.callback (/usr/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:128:46)
    at PushClient.handleParsedMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
    at PushClientParser.<anonymous> (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
    at PushClientParser.emit (events.js:315:20)
    at PushClientParser.onGotMessageBytes (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
    at PushClientParser.handleFullMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
    at PushClientParser.waitForData (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
    at PushClientParser.onGotMessageSize (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
[23/12/2020, 16:54:34] Got SIGTERM, shutting down Homebridge...
(node:1037) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1037) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1037) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by skazzyskills** [comment]
Is your Homebase red lighting?

Shawn Skalinski
sskalinski@icloud.com

**Comment by rdustinb** [comment]
@skazzyskills If you mean in the status it says "home bridge is not running" then yes. It looks like the issue occurred after I restarted my doorbell. The logs indicate the plugin is trying to reuse the same auth token which probably changed because I restarted my doorbell.

**Comment by skazzyskills** [comment]
No, I meant the Homebase 2 unit. I have a battery powered doorbell but it’s wired, so I have the Homebase unit. Anyway, after deleting the plugin it’s gone back to blue light again. I’ll wait for update.


Shawn Skalinski
sskalinski@icloud.com

**Comment by skazzyskills** [comment]
Upon uninstalling the homebase unit came back online. When I reinstalled, my indoor cameras now go offline.
