### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by koen1971** [birkir/homebridge-plugin-eufy-security#22]
**Describe Your Problem:**
complete reinstall homebridge.
no video

**Logs:**
[12/29/2020, 6:12:50 PM] Homebridge is running on port 51180.
[12/29/2020, 6:12:52 PM] [EufySecurityHomebridgePlugin] Adding new accessory: Deurbel
[12/29/2020, 6:14:09 PM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Deurbel
[12/29/2020, 6:14:38 PM] [EufySecurityHomebridgePlugin] Stopped video stream. Deurbel
```
Show the Homebridge logs here, remove any sensitive information.
```
{
    "bridge": {
        "name": "Homebridge 70E1",
        "username": "0E:12:DC:EA:70:E1",
        "port": 51180,
        "pin": "699-34-406"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "username": "xxxxxxxx",
            "password": "xxxxxx",
            "enablePush": false,
            "platform": "EufySecurityHomebridgePlugin"
        }
    ]
}

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.1.6
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by singas77** [comment]
yep no video 
Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:11:58 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:12:36 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:12:36 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:12:36 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:12:54 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:12:54 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:12:54 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:12:56 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:05 AM] [Air Conditioner] Active BEGIN WRITE 0 0
[12/30/2020, 8:13:05 AM] [Air Conditioner] Active WRITE OK 0 0
[12/30/2020, 8:13:32 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:35 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:13:35 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:35 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:13:44 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:13:44 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:44 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:13:49 AM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:53 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:13:53 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:13:53 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 8:14:16 AM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 8:14:16 AM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 8:14:17 AM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell

**Comment by koen1971** [comment]
Do I need to install homebridge-camera-ffmpeg?

**Comment by singas77** [comment]
I have but now can't even sign into eufy app 
login failed request 
will have to wait and see how long eufy takes to get that back up 
[EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by singas77** [comment]
its in the dependancies yes

**Comment by koen1971** [comment]
So install it and no need to configure it?

**Comment by singas77** [comment]
I can't get it to work im using the Eufy app for now 
the read me for home bridge Eufy plug in needs more info if extra config is required ???

**Comment by koen1971** [comment]
Working for me now. Turns out my Mac mini software was to old. Installed Catalina OS. Ffmpeg is now also installed automatically. 

Incan start the video and see the stream. Only no audio yet and I don't get a message on screen form HomeKit when doorbell is activated.

**Comment by singas77** [comment]
ive been on Big Sur so im not sure if its a ops version issue 
also every email address ive associated to the home bridge plug in can no longer log into the Eufy app if I log out and try to log back into Eufy iOS app 
failed to request error ???
waiting for Eufy support responses
