### ISSUE TITLE
 [EufySecurityHomebridgePlugin] registering a push token timed out

### ISSUE THREAD

**Issue by singas77** [birkir/homebridge-plugin-eufy-security#23]
**Describe Your Problem:**

**Logs:**

```
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/30/2020, 7:59:23 AM] [EufySecurityHomebridgePlugin] registering a push token timed out

```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by mbicca** [comment]
Added the plugin and getting this error and video/stream not showing up in Home App (iOS)

Plugin Version: **homebridge-plugin-eufy-security v0.1.6**
Homebridge Version: **v1.1.7**
Node.js Version: **v14.15.3**
NPM Version: **6.14.9**
Operating System: **Ubuntu 20.04.1 LTS**

Error that shows up in Homebridge:
```
[12/29/2020, 9:53:36 PM] [EufySecurityHomebridgePlugin] Restoring existing accessory from cache: Doorbell
(node:21928) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> 20022 - Failed to request.
    at /usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[12/29/2020, 9:54:05 PM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
```

**Comment by singas77** [comment]
yeah I have video issue also osx 11.1

An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 1:53:39 PM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 1:53:39 PM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 1:53:39 PM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 1:53:55 PM] [EufySecurityHomebridgePlugin] Starting video stream: 1280 x 720, 30 fps, 299 kbps Doorbell
[12/30/2020, 1:53:55 PM] [EufySecurityHomebridgePlugin] Failed to start stream: spawn ffmpeg ENOENT Doorbell
[12/30/2020, 1:53:55 PM] [EufySecurityHomebridgePlugin] Stopped video stream. Doorbell
[12/30/2020, 1:53:56 PM] [EufySecurityHomebridgePlugin] An error occurred while making snapshot request: Error: spawn ffmpeg ENOENT Doorbell

**Comment by TheBassfly** [comment]
Same for me here.

**Comment by SSpecken** [comment]
@maddijoyce submitted a commit that seems to solve this issue. But I don't know to integrate and test this with my homeridge installation on Windows. Any hints?

**Comment by maddijoyce** [comment]
Hey @SSpecken the issue I pushed is just that sometimes the "registering a push token timed out" can show up when it's not meant to (because the timeout isn't cancelled when a successful registration occurs.

One thing you can try is looking at the homebridge logs in debug mode.
When I looked at mine, I noticed I was getting a successful push token registration, followed by a "timed out".

I suspect you're also being impacted by a different issue.
