### ISSUE TITLE
Error launching plugin

### ISSUE THREAD

**Issue by amery78** [birkir/homebridge-plugin-eufy-security#29]
**Describe Your Problem:**
Hello everyone and happy new year !
I installed the plugin to use it with my battery EUFY doorbell and I have these errors in my home bridge logs

**Logs:**

(node:26851) UnhandledPromiseRejectionWarning: Error: GCM-Register -> Error=PHONE_REGISTRATION_ERROR
    at PushRegisterService.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-register.service.js:139:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-register.service.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26851) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26851) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Plugin Config:**

{
            "name": "Eufy",
            "username": "log",
            "password": "^password",
            "enablePush": true,
            "platform": "EufySecurityHomebridgePlugin"
        }

**Environment:**

* **Plugin Version**: homebridge-plugin-eufy-security v0.1.6
* **Homebridge Version**: Homebridge v1.1.7
* **Operating System**: macOS

**Comment by amery78** [comment]
Self reply but could be useful for other people ;)
with "enablePush" set to false it's now working.

**Comment by veen89q** [comment]
If this doesn’t work as it did for me, pull the micro sd card out of the raspberry while running, disconnect power, plug micro sd in and run again, connect to Hoobs.local or IP and select Start service from the menu

**Comment by amery78** [comment]
Thx you for your answer, everything works since I set push to false :)
