### ISSUE TITLE
Wired Doorbell Support

### ISSUE THREAD

**Issue by Stichoza** [birkir/homebridge-plugin-eufy-security#3]
Glad that someone created this package finally. Been searching for this on a daily basus from the day I bought the doorbell.

I read through the code and I'm afraid the only supported doorbell is the battery one. Is there a possibility to support wired 2K doorbell also?

**Comment by birkir** [comment]
You can try 0.1.1, I allowed all of the doorbells to be enabled.

I don't have that kind of a device, so I don't know if it works. Please let me know.

**Comment by Stichoza** [comment]
Yaay! 🎉 It discovered a doorbell, but it's now stuck in sigterm-restart loop. From homebridge logs:

```
[02/12/2020, 11:53:08] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at PushClient.callback (/usr/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:91:46)
    at PushClient.handleParsedMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
    at PushClientParser.<anonymous> (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
    at PushClientParser.emit (events.js:315:20)
    at PushClientParser.onGotMessageBytes (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
    at PushClientParser.handleFullMessage (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
    at PushClientParser.waitForData (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
    at PushClientParser.onGotMessageSize (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
[02/12/2020, 11:53:08] Got SIGTERM, shutting down Homebridge...
```

**Comment by Stichoza** [comment]
I tinkered with `dist/platform.js` inside installation and manually added a serial number as a string (I only have one device on my account).

Doorbell was successfully registered and I was even able to start a video stream, but there are some errors in logs:

```
[02/12/2020, 12:54:37] [EufySecurityHomebridgePlugin] Stopped video stream. Test
(node:6215) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6215) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6215) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by moshed** [comment]
I have a wired doorbell as well and would love to help if needed.

**Comment by macuserman** [comment]
Yes super excited about this plugin, I have the wired one as well. So glad someone started working on this, hopefully I can contribute.
