### ISSUE TITLE
Bug video and notification 

### ISSUE THREAD

**Issue by technikosoldat** [birkir/homebridge-plugin-eufy-security#31]
I installed the plugin and nothing works. The video only works out of ten, I don’t have an alert when a person rings at the door. The HomePod doesn't ring either. Do you need special settings in the Eufy application? I hope that an update will soon be made of the plugin

**Comment by skazzyskills** [comment]
There is no HomePod ring...yet. As the files state, you get video live feed. No audio either.

**Comment by karesake** [comment]
With the old 0.1.1 Version the HomePad has ringed!

**Comment by technikosoldat** [comment]
@karesake Is this version 0.1.1 you have? I’ll try to install it to see if it works.

**Comment by karesake** [comment]
The ringing worked with 0.1.1. The problem is that the video stream no longer works with this version and the problem with the notifications at that time is not resolved.

I'm back to 0.1.6 and hope that the HomePod will finally return @birkir

**Comment by skazzyskills** [comment]
Huh?

Shawn Skalinski
sskalinski@icloud.com

**Comment by technikosoldat** [comment]
It doesn’t work with version 0.1.1 for the sounding on the HomePod and I still don’t have an iPhone notification if someone rings. I hope to have an update

**Comment by sverspecht** [comment]
I've just came back to v0.1.1 and now it works as expected: 
I get notification on:
- iDevices
- Apple TV
- Homepods

I even get a picture attached to notification.

After, it's similar behavior than with 0.1.6. Video live feed come sometimes (70% of time) but with 5 or 10 seconds delay.

**Comment by skazzyskills** [comment]
Now we just need everything to come together

Shawn Skalinski
sskalinski@icloud.com

**Comment by PeterAlexander75** [comment]
Wow - .1.1 does appear to work... nice.

**Comment by skazzyskills** [comment]
How do you scale back to .1.1?


Shawn Skalinski
sskalinski@icloud.com

**Comment by PeterAlexander75** [comment]
I’m using homebridge ui on the Mac. Under plugins, there’s an icon which when clicked, included the option to rollback to any prior version. 

The push token timeout doesn’t seem to be an issue in this version. But it seems the notifications are sometimes duplicated and that motion detection /  do rebel press definition isn’t working well. Also, it’s much slower than the official app. And, if you go into the HomeKit app, presses are on for notifications, motion is off. If you turn motion on, it won’t save and reverts back to off upon opening the settings again.

**Comment by sverspecht** [comment]
<img width="523" alt="Capture d’écran 2021-02-02 à 07 42 08" src="https://user-images.githubusercontent.com/21987415/106562143-29d83880-652a-11eb-9a6c-b2e2ca3170d9.png">

(It's in french but, it must be similar in others languages.)

Hello, little update after 2 days. Notifications still works but with empty pictures. I don't get live feed anymore. Maybe there is a problem with a token/authentification to get videos and image

**Comment by sverspecht** [comment]
![IMG_8197](https://user-images.githubusercontent.com/21987415/106628385-0a68fc00-657a-11eb-84fd-f6857c993a85.jpg)

Actually, with this message claiming, someone else viewing live feed, I wonder if the problem juste don't come from a previous non-clean closing feed...

**Comment by sverspecht** [comment]
(node:8538) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo EAI_AGAIN security-app-eu.eufylife.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)

(Use `node --trace-warnings ...` to show where the warning was created)
(node:8538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Ok... It's finally unusable in this version. I'll try to deep into both versions (0.1.1 and 0.1.6) to see if I can (understand and) mix them.

**Comment by karesake** [comment]
Nothing's happening here anymore. Is the developer still interested in it? The old 0.1.1 version works better and more extensively than 0.1.6. No more fixes and no further development. Sorry, but then you could have left it, too.

**Comment by PeterAlexander75** [comment]
Hey, maybe the guy is working on integrating all the suggestions as well as the bug fixes and maybe it is abandoned. But I don't think we should be criticising the dev for trying to build something for the community, whether it worked or not.

**Comment by birkir** [comment]
> Nothing's happening here anymore. Is the developer still interested in it? The old 0.1.1 version works better and more extensively than 0.1.6. No more fixes and no further development. Sorry, but then you could have left it, too.

LOL.

I have other things happening in my life right now and can't spend as much time on open source as I usually do.

I am super happy to accept pull-requests though, and can cut a release on npm as often as you guys like.

Maybe @karesake can help us fixing some of the bugs?

Thanks

**Comment by PeterAlexander75** [comment]
Thanks @birkir  - very much appreciated. Drop a "donation" button on the plugin and I'll be delighted to contribute as a thank you.

**Comment by daviddigregorio** [comment]
Was getting the same situation with 0.1.6. Cameras show up in Homekit but don't load. No notifications. I rolled back to 0.1.1 but now the cameras don't show up at all. Would gladly pay money to get this working.

**Comment by sverspecht** [comment]
We are all agree: this plugin has big potential and we will very happy if it fully work.

@birkir, if we can help you, don’t hesitate. I can try multiple versions, output logs, ...

Sébastien

Le 6 févr. 2021 à 18:51, daviddigregorio <notifications@github.com> a écrit :

﻿

Was getting the same situation with 0.1.6. Cameras show up in Homekit but don't load. No notifications. I rolled back to 0.1.1 but now the cameras don't show up at all. Would gladly pay money to get this working.
