### ISSUE TITLE
no response since update

### ISSUE THREAD

**Issue by skazzyskills** [birkir/homebridge-plugin-eufy-security#37]
**Describe The Bug:**
since updating to newest version, camera has no response. Also, what is new in the update 1.08?

**To Reproduce:**
no response when activating camera.

**Expected behavior:**
for a camera response

**Logs:**
(node:10128) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/web/equipment/start_stream -> ..... - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[12/02/2021, 23:01:36] [EufySecurityHomebridgePlugin] Stopped video stream. Front doorbell
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
{
    "bridge": {
        "name": "Homebridge 55E8",
        "username": "....",
        "port": ...,
        "pin": "..."
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8588,
            "platform": "config"
        },
        {
            "username": "....",
            "password": "...",
            "enablePush": true,
            "platform": "EufySecurityHomebridgePlugin"
        }
    ]
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**:  v14.15.1

* **NPM Version**:  v6.14.8
* **Operating System**:  Raspbian

**Comment by technikosoldat** [comment]
Since the last update, the ringing on the HomePod works as well as the notification on the phone. That was not the case before. But the video doesn't work. Thanks to @Birki for the latest update and I hope to have updates soon, especially so that the video will work and add the door and window sensors.

**Comment by stefaneli** [comment]
I have the same issue as mentioned above. After the update it stopped working. The error in console is slightly different. I tried reinstalling, deleting and installing again and also going back to previous version but nothing helped.
Here is the error that I'm getting: 

(node:14561) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14561) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14561) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by C4ptainMeow** [comment]
I think the Login Servers from Dufy are down, I can't access through the web page as it states every time that the request could not be send. I logged out from App and can't login.
And I think this new Version also works better with Video, as per Yesterday everything worked fine after update. Even the loading time was faster

**Comment by PeterAlexander75** [comment]
I have same error as above. I don't think the login servers are down. There has never been a webpage at https://security-app-eu.eufylife.com/v1/passport/login so far as I know (if that's what you're referring to, @C4ptainMeow.

**Comment by stefaneli** [comment]
The link in my error message is https://mysecurity.eufylife.com/#/login. But when I try to log in, it says wrong email and pass. Not sure what's happening, but this scenario with the server would be the best :)

**Comment by C4ptainMeow** [comment]
@PeterAlexander75 its the website as mentioned by @stefaneli. Im glad he as the same error, as this calms a bit down to hear. You could try the same with logging out of the App and trying to log back in, there you get the Error that the Request failed to login. So no mentioning of wrong User/Password. I already send a request to the Eufy Support, but they are not working on weekends.

**Comment by skazzyskills** [comment]
Working now for me. Anyone else using another account (Guest) with this? Just wondering if this slows down video loading. Also, any way around streaming time limit? I’d like to have it up on my iPad streaming permanently. :-)

Shawn Skalinski
sskalinski@icloud.com

**Comment by stefaneli** [comment]
Definitely issue with the server. Now it works for me also.

**Comment by skazzyskills** [comment]
I just tested it I’m not getting any notifications on any of my HomePods or my iPhone. Once in a while I still get a ‘no response’, so it seems to be taking a long time to load the video, same as before. So basically I haven’t seen any improvements in this update for me.

Shawn Skalinski
sskalinski@icloud.com

**Comment by CGDaveMac** [comment]
Yes, so it looks like a server issue. I cannot login on the website listed above... question is why is the plugin in my hoomebridge setup trying to log in to a different server: https://mysecurity.eufylife.com/api/v1/passport/login ?? I don't see either server location listed in the source code.

**Comment by XiozTzu** [comment]
Same issue as others, no response since update.  I have push turned off.

`[13/02/2021, 11:21:28] [Button Platform] error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.`

Odd thing here is it is reporting a [EufySecurityHomebridgePlugin] error under [Button Platform] is the logging code broken somehow?

I tried turning on push and got the following, FWIW.
```
[EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[13/02/2021, 11:20:50] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
    at PushClient.callback (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:134:46)
    at PushClient.handleParsedMessage (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
    at PushClientParser.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
    at PushClientParser.emit (events.js:315:20)
    at PushClientParser.onGotMessageBytes (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
    at PushClientParser.handleFullMessage (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
    at PushClientParser.waitForData (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
    at PushClientParser.onGotMessageSize (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
```

**Comment by bade99uk** [comment]
I’m no coder so can’t provide the same level of scrutiny.  Never had homepod chime, can ask atv to see doorbell and video does pop up as it dose in homeapp. The video is reminiscent of login to webpage https://mysecurity.eufylife.com/#/login which can be sluggish and unresponsive. When I switched on the push option I was unable to log on for a few days. I believe it maybe bombarding the server and kicks you off for a while? The latest update does not work for me. I have rolled back to pervious version and it’s showing video. Hope this helps.

**Comment by jonlonergan** [comment]
I've noticed that when the pl

> Same issue as others, no response since update. I have push turned off.
> 
> `[13/02/2021, 11:21:28] [Button Platform] error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.`
> 
> Odd thing here is it is reporting a [EufySecurityHomebridgePlugin] error under [Button Platform] is the logging code broken somehow?
> 
> I tried turning on push and got the following, FWIW.
> 
> ```
> [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
>     at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> [13/02/2021, 11:20:50] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
>     at Hash.update (internal/crypto/hash.js:84:11)
>     at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:9:11)
>     at PushClient.callback (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/src/platform.ts:134:46)
>     at PushClient.handleParsedMessage (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:206:26)
>     at PushClientParser.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client.service.js:103:63)
>     at PushClientParser.emit (events.js:315:20)
>     at PushClientParser.onGotMessageBytes (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:150:14)
>     at PushClientParser.handleFullMessage (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:79:22)
>     at PushClientParser.waitForData (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:64:18)
>     at PushClientParser.onGotMessageSize (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/push/push-client-parser.service.js:124:18)
> ```

When I experience this problem, I notice that I am unable to log into the Eufy Security website or the iOS app. I have to wait about 24 hours before my login works again. Once my login starts working again, the plugin starts working again too.

Something may be happening on the server side, like a temporary account lock.

**Comment by CGDaveMac** [comment]
Could be [this](https://www.reddit.com/r/homebridge/comments/jthdaj/request_eufy_doorbell_plug_in/ggpkly2?utm_source=share&utm_medium=web2x&context=3): 
"This one is working for me. Make sure to setup a guest account first, register and test it with the app on your phone. Then sign out and setup the plugin. Important: make sure to disable “Push” for the time being. Failure to follow these steps can cause your account to be locked out for 48 hours."

**Comment by XiozTzu** [comment]
I must have missed the memo, is it recommended to only use this plugin with a guest account?

**Comment by PeterAlexander75** [comment]
> I must have missed the memo, is it recommended to only use this plugin with a guest account?

Since there are issues with accounts being locked and push tokens, it seems best to use a guest account. That way, if it gets locked, it doesn't matter.

Also, if you have lots of Eufy devices and you only want the doorbell to show up in HomeKit, then when you create the guest account, just share the doorbell and nothing else.

The note from the reddit thread seems to work. the camera is in HomeKit. Dare not try and set up push for now.

**Comment by mrota83** [comment]
Same here was working with version 0.16 and since updated to 0.18 not working anymore. Push tokens is off and use guess account.

**Comment by skazzyskills** [comment]
Does anybody have HomePod notifications working? Why is it working for some but not for others?

Shawn Skalinski
sskalinski@icloud.com

**Comment by bmonninkhof** [comment]
Does not work for me either "[EufySecurityHomebridgePlugin] failed to confirm push token"

**Comment by Mike92115** [comment]
> Does anybody have HomePod notifications working? Why is it working for some but not for others? Shawn Skalinski sskalinski@icloud.com
> […](#)

Nothing is working for me and I am using a guest account with push turned off so I am not sure what the issue is that allows it to work for others and I get nothing.

**Comment by PeterAlexander75** [comment]
So, done some digging and account messing about.

You can get everything to work temporarily if:-

1. Remove the Eufy plugin. Restart homebridge.
2. Use a spare email address and from your main Eufy account in the Eufy app, share the doorbell with non-admin access to this new email address
2. Log into the Eufy app with the new email account
3. Log out again.
4. Reinstall the Eufy plugin
5. Log in with the new account
6. Push will work to start with. You'll get HomePod chimes, Apple TV notifications, etc.
7. However, after a while, the account will get locked. It's not clear to me why. Everything will stop working and the plugin will start throwing errors as the account gets locked.
8. If you do not enable push, you'll see the camera in the Home app, and that will work some of the time (not clear why it's not reliable), but the account won't get locked.

**Comment by Basher92** [comment]
Did some digging and trying myself today and I can confirm everything PeterAlexander75 just stated.

**Comment by CGDaveMac** [comment]
I followed the exact steps and still get:
`https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.` on the new account.

**Comment by bmonninkhof** [comment]
> So, done some digging and account messing about.
> 
> You can get everything to work temporarily if:-
> 
> 1. Remove the Eufy plugin. Restart homebridge.
> 2. Use a spare email address and from your main Eufy account in the Eufy app, share the doorbell with non-admin access to this new email address
> 3. Log into the Eufy app with the new email account
> 4. Log out again.
> 5. Reinstall the Eufy plugin
> 6. Log in with the new account
> 7. Push will work to start with. You'll get HomePod chimes, Apple TV notifications, etc.
> 8. However, after a while, the account will get locked. It's not clear to me why. Everything will stop working and the plugin will start throwing errors as the account gets locked.
> 9. If you do not enable push, you'll see the camera in the Home app, and that will work some of the time (not clear why it's not reliable), but the account won't get locked,  but obviously, there'll be no push notifications.

Seems this is not solution, but it proves the problem isn't the Homebridge Eufy plugin, but Eufy itself.

**Comment by deadrubberboy** [comment]
I followed these exact steps too, without actually seeing this post first. I went the extra step of removing the doorbell from "cache" first before uninstalling the plug in. I confirmed I can log in on eufy site and view doorbell with this new guest account. 

Reinstalled the plug in and added new account details. 
In Homebridge I'm still getting the error and the accessory (doorbell) no longer even loads (push was never enabled and is still not - I never used it out of fear of account ban on eufy side).

So... not working for me. I'll wait patiently for a fix. :) I appreciate all of the hard work on this plug in!

**Comment by RadLogan** [comment]
having a similar to above. So I’m new to the Eufy Doorbell and plugin. I’ve never been able to get this plugin to work. I noticed since buying Eufy Doorbell my UN and PW worked when setting up but never worked online and when I singed out I was locked out of my app for about 48 hours where it wouldn’t take any PW not even reset ones. I finally reset the PW and was able to get into the app but still not able to get this plug-in to work. Please help!

**Comment by neumanns** [comment]
First of all, a very big compliment to the developers involved who accept eufy's promise, "the doorbell will be homekit compatible".

I see two problems with the current state of development:
1.) eufy does not allow a permanent external connection to its api.
      if the plugin works, your own eufy account will be deactivated after a short time.

2.) the accessories react differently in the different versions.
  e.g.
   a.) version 0.1.1 homepod doorbell works, doorbell video does not work.
   b.) version 0.1.8 homepod doorbell does not work, doorbell video works.

can the hompod function from 0.1.1 not be transferred to eversion 0.1.8?

I understand very well that the fundamental problem is not with the hombridge plugin developers but with eufy, who are not willing to make their api public.

I wish you every success with the further development and look forward to the next update.

**Comment by 5chm3gz** [comment]
Same issue here..... Following PeterAlexander75  solves the problem temporarily.

**Comment by 5chm3gz** [comment]
Same issue here..... Following PeterAlexander75  solves the problem temporarily.

**Comment by skazzyskills** [comment]
It’s so sporadic. I all of a sudden got notifications on HomePod and phone, then it stopped and camera is unresponsive. Urgh.


Shawn Skalinski
sskalinski@icloud.com

**Comment by asu93** [comment]
I have tried the above and nothing worked for about 5 minutes now nothing.

**Comment by advanliempt** [comment]
Update Homebridge to v1.3.2 en everything is ok again!

**Comment by PeterAlexander75** [comment]
> Update Homebridge to v1.3.2 en everything is ok again!
> 
> Sorry to fast, after a while 't did't works again

Yeah - it seems like functionality wise, the Homebridge 1.3.2 update has made everything work (camera, HomePods, etc). But, the underlying issue with the Eufy accounts being locked remains.

**Comment by RadLogan** [comment]
> > Update Homebridge to v1.3.2 en everything is ok again!
> > Sorry to fast, after a while 't did't works again
> 
> Yeah - it seems like functionality wise, the Homebridge 1.3.2 update has made everything work (camera, HomePods, etc). But, the underlying issue with the Eufy accounts being locked remains.

I’ve never gotten mine to work as I set mine up during that time this issue started. To get yours to work after the Homebridge update did you have to reset your password first since it gets locked?

**Comment by PeterAlexander75** [comment]
> > > Update Homebridge to v1.3.2 en everything is ok again!
> > > Sorry to fast, after a while 't did't works again
> > 
> > 
> > Yeah - it seems like functionality wise, the Homebridge 1.3.2 update has made everything work (camera, HomePods, etc). But, the underlying issue with the Eufy accounts being locked remains.
> 
> I’ve never gotten mine to work as I set mine up during that time this issue started. To get yours to work after the Homebridge update did you have to reset your password first since it gets locked?

I'd disabled it, so my account wasn't locked. I just added the plugin back, knowing my account wasn't locked. The config is very simple:-

            "username": "youremail@helloworld.com",
            "password": "yourpassword",
            "enablePush": true,
            "platform": "EufySecurityHomebridgePlugin"

I have two accounts. The main account and then another I created and shared the doorbell with. I use this "secondary" account for all things plugin related, so that if anything goes wrong, the main account and security system I have all keeps working.

PA

**Comment by asu93** [comment]
Okay, so it appears that homebridge is connecting with eufy with out errors since update, how do I get the door bell to connect with homekit? I have tried adding the accessory with the number provided, I have even tried with a child bridge to no avail

**Comment by Mike92115** [comment]
Even after updating HomeBridge, Node and NPM and using a secondary account that I was able to login with the plugin is still failing for me with the following and disables the secondary account.


[3/8/2021, 12:51:55 PM] [homebridge-plugin-eufy-security] registering a push token timed out
[3/8/2021, 12:52:21 PM] [homebridge-plugin-eufy-security] failed to register push token Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:736) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/8/2021, 12:52:25 PM] [homebridge-plugin-eufy-security] failed to confirm push token

**Comment by joeybaker** [comment]
Since eufy-node-client is deprecated, and eufy-security-client is the new cool kid on the block, I took a look at what they're doing differently. Seems like it's just a question of the headers being sent to the API. The newest headers from eufy-security-client are: https://github.com/bropat/eufy-security-client/blob/master/src/http/api.ts#L29-L44

(as opposed to https://github.com/JanLoebel/eufy-node-client/blob/master/src/http/http.service.ts#L8-L23 )

I bet updating the headers/moving to the new lib would do the trick. Sucks that we'll have to keep those headers frequently updated :\

**Comment by CGDaveMac** [comment]
I took a look in platform.ts and it imports HttpService from eufy-node-client.

eufy-security-client doesn't have HttpService, so I am guessing someone will need to make whatever changes are necessary to make this plugin with with eufy-security-client
