### ISSUE TITLE
Unexpected Error when loading plugin

### ISSUE THREAD

**Issue by jadehamster** [birkir/homebridge-plugin-eufy-security#42]
Running with a guest account, no 2FA. Verified login credentials.

See the following error when loading Homebridge. Doorbell does not appear in list of devices.

node:88665) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:88665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:88665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by CGDaveMac** [comment]
This is a duplicate issue of #37

**Comment by Firefighter2202** [comment]
Looks like the link: https://mysecurity.eufylife.com/api/v1/passport/login is not correct anymore.

**Comment by CameronSmith93** [comment]
Throwing my hat into the ring on this one as well - my doorbell arrived today, was keen to get it up and running and received an error similar to the above.

`(node:26269) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26269) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Fortunately I used a guest account, as I noticed that once that error appears, the account gets locked - from what others are saying, this is for a period of 24 hours.

Not sure how we progress from here if Eufy is doing the blocking on their end.

**Comment by drumnkyle** [comment]
I just tried to set this up and am having the same issue. Any updates? Would love to use this so I can access my doorbell.
