### ISSUE TITLE
Plugin installation problem

### ISSUE THREAD

**Issue by MSDaytona** [birkir/homebridge-plugin-eufy-security#6]
**Describe The Bug:**
Plug-in doesn't seem to install correctly when using it in HOOBS

**To Reproduce:**

**Expected behavior:**
Correct installation

**Logs:**

Show the Homebridge logs here, remove any sensitive information.
07/12/2020, 08:29:15 The requested platform "EufySecurityHomebridgePlugin" was not registered by any plugin.
07/12/2020, 08:29:15 Your config.json is requesting the platform "EufySecurityHomebridgePlugin" which has not been published by any installed plugins.

**Plugin Config:**

Only entered my email address and password
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

* **Plugin Version**: Latest ( as of this morning )
* **Homebridge Version**: I am using  HOOBS in Docker on my Synology NAS
* **Node.js Version**: <!-- node -v -->
* **NPM Version**: <!-- npm -v -->
* **Operating System**:HOOBS in Docker on my Synology NAS

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by cmfrazier** [comment]
Looks like a config.json issue. Can you post that? (Redact sensitive information)￼

**Comment by Gusot80** [comment]
Hello,

Perhaps you can help mei have the same problem, but i also validate before the config.json
{
			"username": "...............",
			"password": "............",
			"name": "Eufy",
			"platform": "EufySecurityHomebridgePlugin"
		},

**Comment by inmaterichard** [comment]
I'm also having the same issue:
```
{
            "username": "...",
            "password": "...",
            "enablePush": true,
            "platform": "EufySecurityHomebridgePlugin"
        }
```

```failed to register push token Error: Request failed: https://security-app-eu.eufylife.com/v1/passport/login -> 26052 - need validate code
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)```

**Comment by seecoolguy** [comment]
any solutions or ideas? I am also running into this problem :-/ with a wired doorbell

```
[3/3/2021, 5:14:07 PM] [EufySecurityHomebridgePlugin] registering a push token timed out
[3/3/2021, 5:14:15 PM] [EufySecurityHomebridgePlugin] failed to register push token Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 26052 - need validate code
    at /usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
